### ISSUE TITLE
sfdisk return 1 with successfully stop sfdisk

### ISSUE THREAD

**Issue by mzhan0170** [karelzak/util-linux#1413] opened 2021-08-17 05:14 UTC
Based on code, seems the return value of this command could be 1 for success case.
So, if scripts uses sfdisk command, and need check the result of success, need check 0 and 1 bothly.
That's maby not consistent with general-purpose of return value 1.

Could you help update the man page of sfdisk to let user notice this?
What's your opinion?

Thanks,
Mark

**Comment by karelzak** [comment] 2021-08-17 08:21
It uses standard EXIT_ stdlib.h macros:
```
$ tail -3 disk-utils/sfdisk.c
	return rc == 0 ? EXIT_SUCCESS : EXIT_FAILURE;
}

$ grep EXIT_ /usr/include/stdlib.h 
#define	EXIT_FAILURE	1	/* Failing exit status.  */
#define	EXIT_SUCCESS	0	/* Successful exit status.  */
```
it means 0 for success. 

Do you have an example when it returns 1 ?

**Comment by mzhan0170** [comment] 2021-08-18 12:45
We run the sfdisk like below scripts, in ksh:

	a=$(print "\
		\nsfdisk ${device.name}<<-EOF\
		\n0,0,0
		\n0,0,0
		\n0,0,0
		\n0,0,0
		\nEOF")

eval ${a}
I always get 1 from the result: $?==1. I 'm not sure if this case match the case of: SFDISK_DONE_EOF

Thanks,
Mark

**Comment by karelzak** [comment] 2021-08-19 10:21
The exit code works as expected.

The problem is that sfdisk does not write an empty disklabel by default (see man page). You have to specify "label: dos" to force it to write an empty label. Unfortunately, there is a bug and this feature does not work as expected when empty partitions are specified (fixed now).

For your use case, you need
```
echo -e "label: dos\n0,0,0\n0,0,0\n0,0,0\n"0,0,0\n |  sfdisk <device>
```

**Closed by karelzak** 2021-08-19 10:21 UTC

**Comment by karelzak** [comment] 2021-08-19 10:22
Thanks for your report!
