### ISSUE TITLE
sfdisk doesn't properly write GPT partition attributes

### ISSUE THREAD

**Issue by poettering** [karelzak/util-linux#380] opened 2016-12-01 01:11 UTC
Let's say I have an image like this:

```
label: gpt
label-id: D8DC3F51-DCAA-4C8C-B3D7-EA6ADC829CF9
device: ./image.raw
unit: sectors
first-lba: 2048
last-lba: 4722654

./image.raw1 : start=        2048, size=      524288, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=2BB397B4-67A1-437D-9581-A84219DBA178, name="ESP System Partition"
./image.raw2 : start=      526336, size=     4196319, type=4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709, uuid=C74237B8-B468-4A1D-874D-DBA9F09D2D3B, name="Root Partition"
```

And now I set bit 60 on the gpt flags for partition 2:

```
$ sfdisk --part-attrs ./image.raw 2 60
```

This works correctly, as sfdisk shows:

```
$ sfdisk --dump ./image.raw
label: gpt
label-id: D8DC3F51-DCAA-4C8C-B3D7-EA6ADC829CF9
device: ./image.raw
unit: sectors
first-lba: 2048
last-lba: 4722654

./image.raw1 : start=        2048, size=      524288, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=2BB397B4-67A1-437D-9581-A84219DBA178, name="ESP System Partition"
./image.raw2 : start=      526336, size=     4196319, type=4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709, uuid=C74237B8-B468-4A1D-874D-DBA9F09D2D3B, name="Root Partition", attrs="GUID:60"
```

However, if I dump this to a file, and write it back, then it doesn't work:

```
$ sfdisk --dump ./image.raw > x
$ sfdisk ./image.raw < x
$ sfdisk --dump ./image.raw
label: gpt
label-id: D8DC3F51-DCAA-4C8C-B3D7-EA6ADC829CF9
device: ./image.raw
unit: sectors
first-lba: 2048
last-lba: 4722654

./image.raw1 : start=        2048, size=      524288, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=2BB397B4-67A1-437D-9581-A84219DBA178, name="ESP System Partition"
./image.raw2 : start=      526336, size=     4196319, type=4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709, uuid=C74237B8-B468-4A1D-874D-DBA9F09D2D3B, name="Root Partition"
```

i.e. the attribute got lost during the restoring of the dump!

Also, there's a bit of difference in what the documentation says the attrs field looks like and what `--dump` actually outputs. Reading the docs I get the impression I am supposed to write "60" to turn on the 60th bit. But --dump outputs this as "GUID:60"... 

(BTW, patching the dump output and replacing `GUID:60` by `60` doesn't help...)

**Comment by karelzak** [comment] 2016-12-02 11:17
What version? It works for me (f24 as well as upstream tree, and we have regression tests for --part-attrs):

Dump created by:
```
# echo -e 'label:gpt\n,524288,U\n,,L\n' | sfdisk image.raw
# sfdisk --part-attrs ./image.raw 2 60
# sfdisk --dump ./image.raw > x
```
and then:
```
# rm -f image.raw; truncate -s 1G image.raw

# sfdisk ./image.raw < x
Checking that no-one is using this disk right now ... OK

Disk ./image.raw: 1 GiB, 1073741824 bytes, 2097152 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> Created a new GPT disklabel (GUID: 386723CB-7276-49F9-A899-21DDDBC54401).
Created a new partition 1 of type 'EFI System' and of size 256 MiB.
./image.raw2: Created a new partition 2 of type 'Linux filesystem' and of size 767 MiB.
./image.raw3: 
New situation:

Device        Start     End Sectors  Size Type
./image.raw1   2048  526335  524288  256M EFI System
./image.raw2 526336 2097118 1570783  767M Linux filesystem

The partition table has been altered.
Syncing disks.
```
Result seems correct:
```
# sfdisk --dump ./image.raw 
label: gpt
label-id: 386723CB-7276-49F9-A899-21DDDBC54401
device: ./image.raw
unit: sectors
first-lba: 2048
last-lba: 2097118

./image.raw1 : start=        2048, size=      524288, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=65AD2B33-BD5A-45FA-8AB1-1B76AE295D3F
./image.raw2 : start=      526336, size=     1570783, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, uuid=5B8B1CF4-A735-4256-892E-E3089283E71F, attrs="GUID:60"
```
Ad format: it's fine to use comma- or space-delimited list of bits. The generated dump format is more precise and uses space and GUID: prefix for unnamed bits. The prefix is optional and you don't have to use it on command line.

**Comment by poettering** [comment] 2016-12-02 16:56
$ rpm -qf /usr/sbin/sfdisk 
util-linux-2.28.2-1.fc24.x86_64

**Comment by poettering** [comment] 2016-12-02 16:59
If I try your commands it works for me too. If i try my commands on my image they do not...

**Comment by poettering** [comment] 2016-12-02 17:00
note that i don't flush out the image, i just write the new partition table on the existing image overriding its original partition table, maybe that's where the difference is from?

**Comment by karelzak** [comment] 2016-12-12 09:30
It's already fixed in the util-linux git tree by commit 8430b9b88426eb3c273b02a2d9505d839913317c. 

The problem has been in the script parser where all after closing quotes (name="....") has been ignored. It seems that workaround for the old version is to use attrs= without quotes and before name=, for example

./image.raw2 : start=      526336, size=     4196319, type=4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709, uuid=C74237B8-B468-4A1D-874D-DBA9F09D2D3B, attrs=GUID:61 name="Root Partition"

... the bugfix will be available in v2.29.1 (in January 2017). Thanks,

**Closed by karelzak** 2016-12-12 09:30 UTC

**Comment by karelzak** [comment] 2016-12-12 09:33
UPDATE: the bugfix is already in v2.29 (Fedora rawhide / f26)

**Comment by poettering** [comment] 2016-12-12 11:12
Excellent! thanks for fixing this! and thanks for pointing me to the work-around!
