### ISSUE TITLE
agetty: backspace/ctrl-u leave first character in logname buffer

### ISSUE THREAD

**Issue by glangshaw** [karelzak/util-linux#454] opened 2017-06-12 11:55 UTC
After commit: 790119b8850ae13bb4254c5096a54b2aeb355b20  both the backspace key and KILL (ctrl-u) leave the first character in the logname buffer.. This character cannot be removed in any way.

Reverting the aforementioned commit restored expected operation.

This was found on Slackware84-current with console in utf8 mode just in case it makes a difference.

**Comment by jnpkrn** [comment] 2017-06-23 08:03
Observed the same undeletable character issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1464148

Originally I thought it is related to kernel log message propagated to the login
screen, but admittedly my memory is weak enough to tell the coincidence from
a common pattern (my brain is usually booting up just as a my machine does).

**Comment by karelzak** [comment] 2017-06-23 09:53
The issue is that we read the first character in non-canonical terminal mode and them switch to the canonical mode, than the first character is unreadable for terminal editing facility (e.g. backspace)...

**Comment by karelzak** [comment] 2017-06-23 12:55
This issue will be fixed in v2.30.1. Thanks!

**Closed by karelzak** 2017-06-23 12:55 UTC

**Comment by glangshaw** [comment] 2017-06-24 11:46
Thank you Karel.  Much appreciated. 

I glanced at the code at the time, expecting some sort of off-by-one in the buffer handling but when I failed to find it I was left scratching my head. :)
