### ISSUE TITLE
unshare --pid=file mounts the parent namespace

### ISSUE THREAD

**Issue by mahkoh** [karelzak/util-linux#798] opened 2019-05-18 13:18 UTC
```
$ touch pid
$ strace unshare --pid=pid true
[...]
unshare(CLONE_NEWPID)                   = 0
getpid()                                = 3299
mount("/proc/3299/ns/pid", "pid", NULL, MS_BIND, NULL) = 0
[...]
```

Maybe I've misunderstood something, but this seems to be rather useless. Shouldn't `proc/3299/ns/pid_for_children` be mounted?

**Comment by karelzak** [comment] 2019-05-20 11:37
If I good understand than ns/pid_for_children expose information about process' children PID namespace to all userspace, because otherwise the has the process itself only and it's invisible from outside.

In time we call unshare() the ns/pid_for_children is always the same as ns/pid. The command unshare(1) does not call fork() by default and the current process (after all the namespace setup) is replaced by exec(), so ns/pid is the final namespace.

I don't think ns/pid_for_children can help us.  IMHO ns/pid_for_children can be attractive for example for nsenter(8) to enter PID namespace maintained by some container init process (etc.).

(And note that ns/pid_for_children is relatively a new thing, year 2017, persistnet namespaces in unshare are supported since year 2015.)

Not a bug from my point of view. Closing.

**Closed by karelzak** 2019-05-20 11:37 UTC
