### ISSUE TITLE
lscpu shows wrong info on POWER9

### ISSUE THREAD

**Issue by xavier1arm** [karelzak/util-linux#698] opened 2018-10-02 11:29 UTC
The "Core(s) per socket" and "Socket(s)" values are swapped. The machine has 1 socket and 10 cores per socket.

$ ./lscpu 
Architecture:        ppc64le
Byte Order:          Little Endian
CPU(s):              80
On-line CPU(s) list: 0-79
Thread(s) per core:  8
Core(s) per socket:  1
Socket(s):           10
NUMA node(s):        1
Model:               2.2 (pvr 004e 0202)
Model name:          POWER9 (architected), altivec supported
Hypervisor vendor:   pHyp
Virtualization type: para
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            10240K
NUMA node0 CPU(s):   0-79

I use rhel 7.5. I tried the system lscpu 2.23.2 and the latest one 2.33-rc1.

**Comment by karelzak** [comment] 2018-10-02 13:32
It would be nice to have snapshot from your /proc. 

https://raw.githubusercontent.com/karelzak/util-linux/master/tests/ts/lscpu/mk-input.sh
Use this script to create a tarball from your /proc and send it to kzak@redhat.com. Thanks!

**Comment by xavier1arm** [comment] 2018-10-02 14:14
Tarball sent.

Thanks,

**Comment by karelzak** [comment] 2018-10-04 11:44
The problem is 
/sys/devices/system/cpu/cpu0/topology/thread_siblings_list where is 0-7 
/sys/devices/system/cpu/cpu0/topology/=core_siblings_list where is also 0-7

lscpu calculates number of 
* cores as "core_siblings / nthreads_siblings", so  8 / 8 = 1 core, 
* sockets as "nsockets = ncpus / nthreads / ncores"; so 80 / 8 / 1 = 10 sockets.

For the box the relation between cores and threads is strange. Maybe it would be possible to ignore core_siblings and use ncpus / nthreads (80 / 8 = 10 cores), but I'm not sure if this is valid in all cases or only if thread_siblings == core_siblings.

**Comment by trevorwhitaker** [comment] 2019-01-16 19:08
Hey karelzak, I have the same issue as xavier1arm. 0-7 in thread_siblings_list and core_siblings_list and socket and cores per socket swapped. Has there been any progression on this?

**Comment by trevorwhitaker** [comment] 2020-02-25 14:21
Hi @karelzak, do you know if this issue still exists?

**Comment by mikey** [comment] 2020-02-26 04:34
There is a fix heading in upstream linux for this https://github.com/linuxppc/linux/commit/a57d19b0e5894acbaa0771f2c1fdc1ff9d5c1939

**Comment by karelzak** [comment] 2020-02-26 10:21
@mikey thanks for your info! Closing.

**Closed by karelzak** 2020-02-26 10:21 UTC
