### ISSUE TITLE
sfdisk --move-data slow

### ISSUE THREAD

**Issue by axet** [karelzak/util-linux#848] opened 2019-08-26 13:22 UTC
Hello!

I choice to use sfdisk to fix partition alignment and move partition by 2 sectors left. sfdisk choice step size of 2048 bytes and it took million hours to complete operation for my 50GB partition. Seems like "optimal" step size algorithm faild, it should take at least 1M step size.

When I did move same parition for several secotors left, it took about 30 minutes to complete.

```
# physical sector size = 4096, logical sector = 512
echo '772305024' | sfdisk /dev/sda -N 3 --move-data # 772305026 -> 772305024
```

Another example, moving partition by 102760448 bytes (200704 sectors) left, sfdisk choice 56320 step, it will take several hours more to complete operation:

```
# sfdisk: util-linux 2.33.1
# Disk: /dev/sdc4
# Partition: 4
# Operation: move data
# Original start offset (sectors/bytes): 2048612352/1048889524224
# New start offset (sectors/bytes): 2048411648/1048786763776
# Area size (sectors/bytes): 1023997810/524286878720
# Sector size: 512
# Step size (in bytes): 56320
# Steps: 9309071
```

iotop gives me 2MB\sec doing fdisk move, same operation with dd gives me 60MB

```
# dd status=progress conv=notrunc bs=1M if=/dev/sdc skip=1037647 seek=1037549 of=/dev/sdc count=462650
38667288576 bytes (39 GB, 36 GiB) copied, 569 s, 68,0 MB/s 
```

**Comment by karelzak** [comment] 2019-08-28 10:00
It really seems lake stupid sfdisk decisision to use so small step size. I'll try to reproduce and fix it. Thanks for your report.

**Comment by karelzak** [comment] 2019-09-06 10:10
I read it more carefully now ... the reason for so small step is that the source and target area are so close (e.g. 1-2 sectors). The move code tries to be safe for situation when sfdisk (or all system) crash, so it does not keep any data *only* in memory, so everything in memory is also in source area too  although the whole areas overlap. Maybe this concept is too paranoid ... I need to think about it :-)

**Comment by karelzak** [comment] 2019-09-06 10:31
OK, plan:
- use large buffer aligned to optimal-sector I/O
- assume that after crash data in-memory will lost
- do not use fsync() by default
- add --move-use-fsync
- add --move-use-directio 
- add progress line

**Comment by axet** [comment] 2019-09-06 11:14
Copying takes a time and longer it gets, makes higher chance to hit a crash. When 30 minutes become 1 day for "safety" reasons, it works opposite. It seems you agreed on that.

BWT: dd with 1M buffer works 2x time after even when sfdisk decide to use 1M buffer. Maybe sfdisk have more issues related to moving partitions than just a small buffer. I guess it is not hard to reproduce having booth sample commands (sfdisk and dd).

Anyway I glad to have console option to move partition, since recent distro can't do sector percice operations and dd only works when moving data to the left (it can't reverse (from last to first sector) reading/writing data).

**Comment by karelzak** [comment] 2019-09-06 13:12
There is fsync() in sfdisk move loop... This is probably reason why it (was) so slow also with 1MiB buffer. 

I don't have time to check the speed now, but I'd like to add MiBs-per-second to the progress bar, so we will see :-)

**Comment by axet** [comment] 2019-09-06 17:23
fsync sync files system to disk, it has nothing to do with direct device access. ops... 😊 

> fsync() transfers the file referred to by the file descriptor fd to the disk device

http://man7.org/linux/man-pages/man2/fdatasync.2.html

**Comment by karelzak** [comment] 2019-09-30 10:30
OK, so now it's with progress bar and speed is >50MiB/s and  17.0 MiB/s with --move-use-fsync on the same device.

Thanks for your report and comments. Closing as resolved.

**Closed by karelzak** 2019-09-30 10:30 UTC

**Comment by axet** [comment] 2020-01-20 14:35
@karelzak Hello! I tried your recent release and it corrupt my linux partition. Can you check if new buffer size 1M does not overlap partition during move? I did move my windows partition to the left in about 4gb, and next linux partition no longer mountable. I remember step size was 1M and I do not remember any sector overlaps it suppose to be last step issue (moving more sectors from aligned partition). I have to use --force parameter because it is same disk I'm running linux on. This is result partition map:

Device         Start       End   Sectors   Size Type
/dev/sda1         40    409639    409600   200M EFI System
/dev/sda2     409640 419840039 419430400   200G unknown
/dev/sda3  419840040 522236891 102396852  48,8G Microsoft basic data
/dev/sda4  532313012 977105023 444792012 212,1G Linux filesystem
