### ISSUE TITLE
enabling libcryptsetup dependency (for verity) causes conflicts with other libraries

### ISSUE THREAD

**Issue by smcv** [karelzak/util-linux#1081] opened 2020-06-29 14:27 UTC
Until recently, libmount was a low-level library with few dependencies, that could be safely depended on by things like GLib.

The addition of the optional libcryptsetup dependency changes that somewhat. There seem to be two main problem areas causing crashes in distributions that have enabled it, such as recent development versions of Debian and Ubuntu:

* The json-c library contains symbols that collide with other JSON libraries such as libjansson (akheron/jansson#523, json-c/json-c#621) and json-glib ([json-glib#33](https://gitlab.gnome.org/GNOME/json-glib/-/issues/33)), because it seems every implementation of JSON in C has chosen to use the `json_` namespace. This is particularly troublesome for anything that depends on json-glib, which depends on GLib, which depends on libmount, which depends on libcryptsetup, which depends on json-c, almost guaranteeing symbol conflicts.

* libcryptsetup's default/recommended OpenSSL backend for crypto has symbol conflicts with anything that statically links a different version of OpenSSL, which seems to be popular in the proprietary software world (Steam and Minecraft are known to be affected). ValveSoftware/steam-for-linux#7223 and ValveSoftware/steam-for-linux#6861 are examples of this.

I don't know which project(s) should take action to solve this, but I'm trying to make sure all the upstreams involved in this collision are at least aware that there's a problem, so that whatever action is taken can be somewhat coordinated.

One way that this might be solved within libmount (if that is considered to be a desirable place to solve it) would be to move the verity feature into a helper executable, or perhaps into a dlopened module that is loaded with `RTLD_LOCAL` to avoid it interfering with symbol resolution in the flat default ELF namespace.

Another possible solution, if the verity feature is mostly of interest to embedded or special-purpose distributions, would be to recommend that general-purpose distributions disable that feature.

**Comment by smcv** [comment] 2020-06-29 14:29
> libcryptsetup's default/recommended OpenSSL backend for crypto has symbol conflicts with anything that statically links a different version of OpenSSL

OpenMandriva appears to have worked around this by [using a non-default crypto backend in libcryptsetup](https://github.com/ValveSoftware/steam-for-linux/issues/6861#issuecomment-650981297), which doesn't seem like the ideal solution.

**Comment by mbiebl** [comment] 2020-06-29 15:02
Another application affected by this is NetworkManager. 
They worked around the jansson/json-glib issue by dlopening libjansson. But are now affected by the libmount1->libjson-c clash as well, see https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/453

It feels wrong, if individual applications have to play whack-a-mole and have to work around this issue individually by dlopening the affected libraries. An approach like symbol versioning the json libraries seems more desirable to fix those issues for good.

**Comment by smcv** [comment] 2020-06-29 15:27
> An approach like symbol versioning the json libraries seems more desirable to fix those issues for good

I would like to see that happen in addition to any solutions that might happen in libmount or elsewhere, and I suggested it on the json-c and jansson issues. The json-glib maintainer already rejected it, although I'm hoping that that was due to a misunderstanding of how high-maintenance it would be.

**Comment by smcv** [comment] 2020-06-29 17:37
> An approach like symbol versioning the json libraries seems more desirable to fix those issues for good

https://github.com/json-c/json-c/pull/639, https://github.com/akheron/jansson/pull/540, https://gitlab.gnome.org/GNOME/json-glib/-/merge_requests/28 are attempts at this. Because they all change the library's ABI (in a backwards-compatible but not forwards-compatible way), they all require upstream maintainer input and should not be done downstream in distros.

**Comment by smcv** [comment] 2020-06-29 17:51
> One way that this might be solved within libmount (if that is considered to be a desirable place to solve it) would be to move the verity feature into a helper executable, or perhaps into a dlopened module that is loaded with RTLD_LOCAL

(cc @bluca who mentioned a similar plan on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951048)

**Comment by bluca** [comment] 2020-06-29 18:00
> > One way that this might be solved within libmount (if that is considered to be a desirable place to solve it) would be to move the verity feature into a helper executable, or perhaps into a dlopened module that is loaded with RTLD_LOCAL
> 
> (cc @bluca who mentioned a similar plan on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951048)

Thanks for the ping Simon - as it was mentioned by Michael on that ticket the new dependency chain, aside from causing those bugs to surface, also increases the size of the minimal Debian bootstrap by 5.6MB (~2.5%). So even if all bugs are solved, it might still be desirable to change the implementation to dlopen() instead of linking to libcryptsetup.

@karelzak what's your take on this?

Thanks!

**Comment by smcv** [comment] 2020-06-29 18:15
I also suggested mitigating this by making GLib dlopen libmount instead of linking it the normal way (on https://gitlab.gnome.org/GNOME/glib/-/issues/2147). A GLib maintainer didn't like that plan, and expressed a desire for libmount to remain low-level and safe to depend on directly, without bringing in crypto and JSON libraries.

**Comment by bluca** [comment] 2020-06-29 21:18
I've given a shot at moving to dlopen, seems to work as expected on my machine at least. PR is linked.

Aside from that, I do very much agree with Michael: this symbol clashing should really be solved at its source in the json libraries. If it's not for this, it will happen again for a different combination, and it might not be as easy to untangle.
And regarding the vendorized old libssl with static linkage in certain applications... let's just say I really hope your efforts to educate the vendors bear fruits, as this issue is probably not the scariest surprise that practice might bring on its users :-)

**Comment by tpgxyz** [comment] 2020-06-30 07:19
Why not dlopen() json-c in cryptsetup ?
Second we found now drawbacks of using kernel as a crypto backend for cryptsetup. At least we do not pull whole SSL stack just to uncrypt disks :)

**Comment by smcv** [comment] 2020-06-30 08:48
> Why not dlopen() json-c in cryptsetup ?

Practical reason: the API surface area between libmount and libcryptsetup is a lot smaller than the API surface area between libcryptsetup and json-c. The less dlsym() is needed, the better.

Another practical reason: that only solves the JSON side of things, not SSL.

Conceptual reason: cryptsetup interactions are only a small, optional and experimental part of libmount (needed for automatic setup of dm-verity volumes), while JSON is a much larger part of cryptsetup, due to its use in LUKS2 headers. If libcryptsetup is missing (and dlopen would fail), most uses of libmount will still work; but if json-c is missing, libcryptsetup will be unable to mount cryptsetup volumes created with default options, which sounds a lot like "doesn't work" to me.

> Second we found [no?] drawbacks of using kernel as a crypto backend for cryptsetup.

The cryptsetup 1.3 release notes describe it as "very slow for this type of operation", although that might be outdated information. (I am not a cryptsetup expert, I'm just trying to fix regressions that were triggered by cryptsetup support being enabled.)

**Comment by smcv** [comment] 2020-06-30 08:51
> this symbol clashing should really be solved at its source in the json libraries

I agree, and I am trying to make it happen; but as far as I can see, it cannot be solved this way until the upstream maintainers of three separate libraries, at least one of which has two parallel build systems, all take action. This is not a quick thing to do.

**Comment by smcv** [comment] 2020-06-30 08:54
> And regarding the vendorized old libssl with static linkage in certain applications... let's just say I really hope your efforts to educate the vendors bear fruits, as this issue is probably not the scariest surprise that practice might bring on its users

I agree, but it is not my decision. It's up to those vendors, and we (as in the people involved in this issue, or Debian, or the open source community) cannot force them to do the right thing.

**Comment by karelzak** [comment] 2020-06-30 08:56
Oh, guys -- this is workaround congress -- dlopen to each family :-)

dlopen() is a nice thing if you want to use (for example 3rd party) modules in your code, but it's pretty ugly to use it as a workaround for badly maintained libs. 

If I good understand, the problem is not libmount + libcryptsetup -- the issue is:

*  anything that statically links a different version of OpenSSL -- sorry, but this is not our fight ...

* missing symbols versioning in json-c and/or glib-json -- the solution is obvious, fix this library! All you need is one file with symbols, a unique name-version prefix, and use it for compilation. It's 10 minutes of work. It's strange to replace this trivial change by dlopen() in other libs, maintain extra code in libmount (or another library), force distros to maintain obscure dependencies, etc.

* size of libmount -- if you care about it, then don't use --with-cryptsetup. It's optional and not enabled by default. (My long term goal is to add some ./configure option to build minimalistic libmount without verity, btrfs, loopdevs and blkid, but it's a different story. We can also move all this functionality to modules, but it will require extra API for modules, etc. -- again, nothing related with the json problem).

I'm ready to help json-c guys to fix the problem, and I'm not ready to work around it by dlopen(). If json-c maintainer won't care then we can think about another solution.

**Comment by karelzak** [comment] 2020-06-30 09:16
It seems @smcv is already trying to help json-c project. Thanks!

See https://github.com/json-c/json-c/issues/621 and https://github.com/json-c/json-c/pull/639.

**Comment by mbroz** [comment] 2020-06-30 09:27
Just a note from the libcryptsetup maintainer:
- JSON is needed for LUKS2, this is a core functionality, so dlopen() in libcryptsetup is not a solution
- json-c library need to learn how to properly version symbols
- please do not switch default crypto backend in libcryptsetup as a workaround here - there could be security consequences (if the backend is slower, you will get lower number of KDF iterations etc), moreover there are some incompatibilities (missing algorithms). We have OpenSSL default for a reason, second fully supported backend is gcrypt. If a distro decides to use other backends (kernel, nettle, ...), it works but functionality could be limited.
- if anyone links a static library, then it must link statically other dependeces. Really, to use two OpenSSL versions in one project is just a very bad idea.

Thanks @karelzak for leading the proper solution here ;-)

**Comment by ebassi** [comment] 2020-06-30 09:53
> If I good understand, the problem is not libmount + libcryptsetup -- the issue is:

The issue is that libmount's functionality is really a low level API that is used in foundational libraries like GLib, which try to be as conservative as possible when it comes to deep, nested dependencies for a variety of reasons—one of which is that C is a terrible language that has a flat namespace for its symbols; and another one that ELF is a terrible format that uses the same approach. This means that the more dependencies you accrue at the bottom of the stack, the higher the chances of something weirdly breaking at the upper layers, with fixes that may take years to arrive, if they ever do. Now we have to update libmount and GLib, and everything else that depends on them, in lock-step.

GLib uses libmount to list mount points in a reliable way, to avoid parsing a bunch of random files. Adding a whole crypto library to the mix makes us *less* likely to rely on libmount, given the amount of dependencies it strings along.

One solution that accommodates the needs of libmount maintainers might be to split libmount into two separate libraries—one to inspect the mount points, the other to operate on them. The former would not have to depend on libcryptsetup and its dependencies; the latter could do whatever it wants.

**Comment by ebassi** [comment] 2020-06-30 09:59
>     * All you need is one file with symbols, a unique name-version prefix, and use it for compilation.

This is enormously disingenuous. Symbol versioning is:

 - an additional burden on maintainers
 - not a common operation *anywhere*
 - still bolted on in terms of build systems and language capabilities
 - respected, last time I checked, only by GNU's libc and linker

Only very, very few libraries use it because of these reasons, so saying "just use a symbol file" like it's the easiest thing in the world with zero side effects and effort is fairly disrespectful.

**Comment by smcv** [comment] 2020-06-30 10:02
To be clear, my goal here is for programs to stop crashing. I am not a maintainer of any of the components involved, and I don't have any particular attachment to a solution being in any particular place, as long as there's a solution *somewhere* (it's no good if the maintainer of each component wants me to change the next component around the circle instead).

When dealing with a bad interaction between two components it's often most robust to address it in both places; by my count this is currently a bad interaction between 9 components, not all of which we are technically or legally able to change. I'm trying to provide reasonable merge requests in as many places as I can, and useful advice in others, in the hope that enough of them are acted on that things stop crashing.

If anyone reading this is good at compatibility with old versions of CMake, I would appreciate help on json-c/json-c#639 and akheron/jansson#540.

**Comment by mbiebl** [comment] 2020-06-30 10:16
> Only very, very few libraries use it because of these reasons,

I would argue, that most of those library maintainers are not using it, because they don't know about symbol versioning. At least that is my experience when talking to them when this topic comes up.
Checking https://codesearch.debian.net, there are 580 packages using `-Wl,--version-script` and a couple using `-Wl,--default-symver`. Sure, there a couple of false positives in that simple search, but this is far from "very, very few".

**Comment by ebassi** [comment] 2020-06-30 10:20
> because they don't know about symbol versioning

Or they know, and have been bitten multiple times by the mess that it made when it was introduced in places like libxml2; but this is entirely beside the point: I *honestly* don't care about symbol versioning, except that I rather not use it.

The issue, here, is adding a complex dependency tree to a small, low level library.

**Comment by karelzak** [comment] 2020-06-30 12:01
> The issue, here, is adding a complex dependency tree to a small, low level library.

It's optional, it's disabled by default... you cry in a bad place. Don't use it. It's so simple -- for example, Fedora does not use it (yet).

I have not a problem preparing some long-term solutions to split the library or use modules, but I'll not do it now to fix someone's mess with symbols or to fix someone's decision to enable this complex feature. It's not a trivial change, we need time to think about it. The symbols versioning is a simple and right-now solution.

**Comment by ebassi** [comment] 2020-06-30 12:09
> It's optional, it's disabled by default... you cry in a bad place. Don't use it. It's so simple

First of all, you're being very rude.

Secondly: GLib cannot control how libmount is built, so we cannot control whether something is disabled—even if it's off by default.

As for "don't use it": libmount is one of our dependencies; it's optional, so we can get around it. We'd rather keep the feature of being able to parse the mounted devices table without having to copy the code in libmount.

**Comment by karelzak** [comment] 2020-06-30 12:24
> > It's optional, it's disabled by default... you cry in a bad place. Don't use it. It's so simple
> 
> First of all, you're being very rude.

Sorry, if it sounds rude (it's really not my intention) -- but for me, all this discussion does not make sense.

> Secondly: GLib cannot control how libmount is built, so we cannot control whether something is disabled—even if it's off by default.

I guess it's downstream (distros) decision to enable this feature, why we discuss it at upstream?

> As for "don't use it": libmount is one of our dependencies; it's optional, so we can get around it. We'd rather keep the feature of being able to parse the mounted devices table without having to copy the code in libmount.

It's absolutely fine that glib uses libmount (and thanks for this, really), but you cannot blame upstream for a way how downstream compile our code. 

@bluca suggested some way how to temporarily resolve it, but although we will use dlopen() the problem with messy symbols in the libraries will NOT disappear. Again, all this is workaround,  one day you will see the problem in another place...

**Comment by smcv** [comment] 2020-06-30 13:26
> I guess it's downstream (distros) decision to enable this feature

It is, but that decision has to be influenced by the various upstreams involved and what they need. The maintainers of the util-linux package in Debian were asked to enable it, they did so, and now programs are crashing. I believe the short-term plan is to disable the feature again while we try to sort out this interaction between multiple components (but apparently it isn't straightforward to revert right now because it has become entangled with an unrelated transition). I'm in the middle, trying to mitigate the problem.

I'm not trying to assign blame here - in fact, I'm trying hard *not* to assign blame. I would appreciate it if the various maintainers could try to see each other's points of view and acknowledge them as having some validity, even if you don't agree on the relative priorities of the factors involved (for example, on whether the maintenance cost of versioned symbols is greater or less than the benefit). The more adversarial this becomes, the less energy I will have for trying to help to resolve it.

If dm-verity users want libmount to have the dm-verity feature, while GLib maintainers/users expect a libmount that does not have the extra dependencies that this feature implies, then it isn't currently possible for both of those groups to have what they want. Debian is a general-purpose distribution, so neither of those requests is obviously more important than the other (at least, not obvious to me, a bystander who just wants the distro as a whole to work). At the moment it seems like *neither* group is getting what they want, which ... I suppose is at least unbiased? :-) But the result is programs crashing.

If the upstream maintainers of util-linux say something like "this is a niche feature that shouldn't be enabled, except in special-purpose embedded distros", then that's useful information that I can take back to Debian. Conversely, if the maintainers of util-linux say "you can't rely on libmount not to have non-trivial dependencies", then that's useful information I can take to GLib maintainers upstream and/or downstream, who might decide on that basis that they want to avoid depending on it.

**Comment by karelzak** [comment] 2020-07-01 07:13
The long term solution (>=v2.37) is to create a new libmount API for plugins to prepare block device and use it for dm-verity and loopdevs. This change will allow us to keep all verity stuff (and dependencies) in a separate subpackage, and install it optionally in downstream distros.

The temporary solution (for v2.36) will be --with-crypsetup=dlopen workaround.

Note that motivation for all this is to keep libmount usable on places where size and dependencies matter. I still assume that JSON guys will do the homework and provide ABI without collisions -- it's strange to assume that people will use dlopen.

**Comment by smcv** [comment] 2020-07-01 15:44
> The long term solution (>=v2.37) is to create a new libmount API for plugins to prepare block device and use it for dm-verity and loopdevs.

Thanks. That sounds ideal, assuming the plugins are loaded with `RTLD_LOCAL`, and/or "lazily" so that they are only in the process space of libmount users that actually mount or unmount a device (as opposed to just enumerating mounts, like GLib does).

> The temporary solution (for v2.36) will be --with-crypsetup=dlopen workaround.

That also sounds good: it has the same desirable property that users of libmount for mount-enumeration don't load the extra libraries.

> I still assume that JSON guys will do the homework and provide ABI without collisions

I hope so too, and I'm trying to help them to do so.

**Closed** 2020-07-08 08:13 UTC
